AWSTemplateFormatVersion: "2010-09-09"
Description: Basic layer one resources
Parameters: 
  Name: 
    Type: String
    Description: The name prefix for all resources.
    Default: ""

Resources:
  LayerOne:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${Name}-LayerOne
      GroupDescription: Layer One Security Group
      VpcId: {'Fn::ImportValue': !Sub 'layer-zero-VPCId'}
      Tags:
        - Key: Name
          Value: !Ref Name
  SecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref LayerOne
      IpProtocol: tcp
      SourceSecurityGroupId: !Ref LayerOne
      CidrIp: 0.0.0.0/0
      FromPort: 80
      ToPort: 80
# Outputs:
