AWSTemplateFormatVersion: "2010-09-09"
Description: Basic layer one resources
Parameters: 
  Name: 
    Type: String
    Description: The name prefix for all resources.
    Default: ""

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub LayerOne-${Name}-EC2
      GroupDescription: Layer One EC2 Security Group
      VpcId: {'Fn::ImportValue': !Sub 'layer-zero-VPCId'}
      Tags:
        - Key: Name
          Value: !Ref Name

  LBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub LayerOne-${Name}-LB
      GroupDescription: Layer One LB Security Group
      VpcId: {'Fn::ImportValue': !Sub 'layer-zero-VPCId'}
      Tags:
        - Key: Name
          Value: !Ref Name

  LBSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref LBSecurityGroup
      IpProtocol: tcp
      CidrIp: 0.0.0.0/0
      FromPort: 80
      ToPort: 80

  LBSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref LBSecurityGroup
      IpProtocol: tcp
      CidrIp: 0.0.0.0/0
      FromPort: 80
      ToPort: 80
    
  EC2SecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EC2SecurityGroup
      IpProtocol: tcp
      SourceSecurityGroupId: !Ref LBSecurityGroup
      FromPort: 80
      ToPort: 80
      Description: Allow traffic from LB to EC2

  EC2SecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref EC2SecurityGroup
      IpProtocol: tcp
      CidrIp: 0.0.0.0/0
      FromPort: 80
      ToPort: 80
      Description: Allow traffic from EC2 to LB

# Outputs:
