name: deploy-cloudformation

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '**/README.md'

permissions: read-all
jobs:
  deploy:
    name: 'continuous-integration'
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ secrets.IAM_ROLE }}
        role-session-name: AWSSession
        aws-region: us-east-2

    - name: Deploy Layer Zero to AWS CloudFormation
      run: |
        aws cloudformation deploy \
          --template ./templates/layer-zero.yaml \
          --stack-name layer-zero \
          --parameter-overrides file://./parameters/layer-zero.json \
          --role-arn ${{ secrets.CFN_ROLE }} \
          --no-fail-on-empty-changeset

    - name: Deploy Layer One to AWS CloudFormation
      run: |
        aws cloudformation deploy \
          --template ./templates/layer-one.yaml \
          --stack-name layer-one \
          --parameter-overrides file://./parameters/layer-one.json \
          --role-arn ${{ secrets.CFN_ROLE }} \
          --capabilities CAPABILITY_NAMED_IAM \
          --no-fail-on-empty-changeset